name: SyncSpace Nuxt Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:
  ci:
    name: CI/CD Pipeline
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun-
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      
      - name: Run Biome check (lint + format)
        run: bun biome lint --write app --max-diagnostics=none
      
      - name: Type check
        run: bun run typecheck
      
      - name: Run tests
        run: bun run test
      
      - name: Build application
        run: bun run build
      
      - name: Generate static site
        run: bun run generate

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy to production
        run: echo "Deploy to production"
        # Ajoutez vos étapes de déploiement ici